#!/bin/bash

PROJECT=`printf '%q\n' "${PWD##*/}"`
CLEAR='\033[0m'
GREEN='\033[1;32m'
RED='\033[0;31m'

if [[ ! $PROJECT = osb-* ]]; then
    echo "Please execute from a liferay OSB- project"; return "1";
fi

SRC_DIR=$(pwd)
DIRS=`git ls-files | grep build.gradle | xargs dirname`

deployAll() {
    for dir in $DIRS; do
        if [[ ! "." = $dir ]]; then
            cd $dir
            echo -e "\n${GREEN}CD to $dir${CLEAR}\n"
            rungradle clean deploy || echo -e "${RED}ERROR: gradle clean deploy failed.${CLEAR}"
            cd $SRC_DIR;
        fi
    done
}

while true; do
    read -p "Do you wish to deploy all modules in $PROJECT?" yn

    case $yn in
        [Yy]* ) deployAll; break;;
        [Nn]* ) exit 0; break;;
        * ) echo "Please answer yes or no.";;
    esac
done

cd $SRC_DIR