#!/bin/bash

echo "This is echoing from polly-start"
echo "Script file is at /Users/joshua/dotfiles/scripts/polly-start"
echo "Symlink is at /Users/joshua/dotfiles/nscript-links/polly-start"

cd ~/programming/pollyex/lxapp && source venv/bin/activate
DEBUG=True python manage.py runserver &
#celery -A app worker -l debug --without-gossip --without-mingle --without-heartbeat -Q celery,user_ux,encompass,encompass_lockdesk &
cd frontend && npm run start