#!/bin/bash

ticketNumber=$1
desc=$(gh issue view $ticketNumber --json title --template '{{.title}}' | xargs echo | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:][:space:]' | tr ' ' '-' )
branchName="$(whoami)-$ticketNumber-$desc"
defaultBranch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')

echo "Branch name: $branchName"
echo "Default branch: $defaultBranch"

git checkout -b "$branchName" "origin/$defaultBranch"
