#!/bin/sh
echo "Deprecated... Update this script to use"
exit 0

xrandr --output LVDS-1-1 --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1-1 --off --output VGA-1-1 --off --output DP-1 --off --output DP-1-1 --off --output DP-0 --off
