#!/bin/bash

echo "This is echoing from zmk-env"
echo "Script file is at /Users/joshua/dotfiles/scripts/zmk-env"
echo "Symlink is at /Users/joshua/dotfiles/nscript-links/zmk-env"

if [ $(uname) != "Darwin" ]; then
  echo "This script is written for MacOS development, modify this for your current system"
  exit 1
fi

echo "Setting ZEPHYR_TOOLCHAIN_VARIANT to gnuarmemb"
export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
echo "ZEPHYR_TOOLCHAIN_VARIANT is set to $ZEPHYR_TOOLCHAIN_VARIANT"

echo "Setting GNUARMEMB_TOOLCHAIN_PATH to /usr/local"
export GNUARMEMB_TOOLCHAIN_PATH=/usr/local
echo "GNUARMEMB_TOOLCHAIN_PATH is set to $GNUARMEMB_TOOLCHAIN_PATH"

echo "Sourcing zephyr-env.sh"
source "$HOME/programming/zmk/zephyr/zephyr-env.sh"